In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [2]:
# read expression data
expr = pd.read_csv('data/TCGA.HNSC.expression.txt', sep='\t', header=0, index_col=[0,1])
print("expression data shape: ", expr.shape)
# read meta data
meta = pd.read_csv('data/TCGA.HNSC.metadata.txt', sep='\t', header=0, index_col=0)
print("meta data shape: ", meta.shape)
# get meta data per sample
meta = expr.reset_index()[['patient_id','sample_id']].join(meta, on='patient_id').set_index(['patient_id','sample_id'])
print("meta data shape: ", meta.shape)
meta.head()


expression data shape:  (545, 20531)
meta data shape:  (500, 18)
meta data shape:  (545, 18)


type  \
patient_id   sample_id                            
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07  HNSC   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07  HNSC   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07  HNSC   
TCGA-BA-4076 TCGA-BA-4076-01A-01R-1436-07  HNSC   
TCGA-BA-4077 TCGA-BA-4077-01B-01R-1436-07  HNSC   

                                           age_at_initial_pathologic_diagnosis  \
patient_id   sample_id                                                           
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07                                 66.0   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07                                 69.0   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07                                 49.0   
TCGA-BA-4076 TCGA-BA-4076-01A-01R-1436-07                                 39.0   
TCGA-BA-4077 TCGA-BA-4077-01B-01R-1436-07                                 45.0   

                                           gender                       race  \
patient_id   sample_id                                                         
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07    MALE  BLACK OR AFRICAN AMERICAN   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07    MALE                      WHITE   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07    MALE  BLACK OR AFRICAN AMERICAN   
TCGA-BA-4076 TCGA-BA-4076-01A-01R-1436-07    MALE                      WHITE   
TCGA-BA-4077 TCGA-BA-4077-01B-01R-1436-07  FEMALE                      WHITE   

                                          ajcc_pathologic_tumor_stage  \
patient_id   sample_id                                                  
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07                   Stage IVA   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07                   Stage IVA   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07                   Stage III   
TCGA-BA-4076 TCGA-BA-4076-01A-01R-1436-07             [Not Available]   
TCGA-BA-4077 TCGA-BA-4077-01B-01R-1436-07                   Stage IVA   

                                                             histological_type  \
patient_id   sample_id                                                           
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07  Head & Neck Squamous Cell Carcinoma   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07  Head & Neck Squamous Cell Carcinoma   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07  Head & Neck Squamous Cell Carcinoma   
TCGA-BA-4076 TCGA-BA-4076-01A-01R-1436-07  Head & Neck Squamous Cell Carcinoma   
TCGA-BA-4077 TCGA-BA-4077-01B-01R-1436-07  Head & Neck Squamous Cell Carcinoma   

                                          histological_grade tumor_status  \
patient_id   sample_id                                                      
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07                 G2   TUMOR FREE   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07                 G3   WITH TUMOR   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07                 G2   WITH TUMOR   
TCGA-BA-4076 TCGA-BA-4076-01A-01R-1436-07                 G2   WITH TUMOR   
TCGA-BA-4077 TCGA-BA-4077-01B-01R-1436-07                 G2   WITH TUMOR   

                                          vital_status   OS  OS.time  DSS  \
patient_id   sample_id                                                      
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07        Alive  0.0    102.0  0.0   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07         Dead  1.0    462.0  1.0   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07         Dead  1.0    283.0  1.0   
TCGA-BA-4076 TCGA-BA-4076-01A-01R-1436-07         Dead  1.0    415.0  1.0   
TCGA-BA-4077 TCGA-BA-4077-01B-01R-1436-07         Dead  1.0   1134.0  1.0   

                                           DSS.time  DFI  DFI.time  PFI  \
patient_id   sample_id                                                    
TCGA-4P-AA8J TCGA-4P-AA8J-01A-11R-A39I-07     102.0  NaN       NaN  0.0   
TCGA-BA-4074 TCGA-BA-4074-01A-01R-1436-07     462.0  NaN       NaN  1.0   
TCGA-BA-4075 TCGA-BA-4075-01A-01R-1436-07     283.0  NaN       NaN  1.0   
TCGA-BA

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import MDS, TSNE
import umap
from sklearn.cluster import KMeans
from sklearn.metrics.cluster import normalized_mutual_info_score


# Handle missing values in metadata
metadata = meta.fillna("Unknown")






/data/space1/BooleanLab/Atishna/ece204_project1/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
label_group=meta.columns[7]

In [ ]:
data = pd.read_csv('~/data/' + filename)

label_group = data[(data.shape[0] - 12): (data.shape[0] - 11)] 

In [4]:
from anndata import read_h5ad
adata = read_h5ad('data/TCGA.HNSC.embedded.h5ad')
embedding_pca=adata.obsm['pca'] # PCA embedding
embedding_mds=adata.obsm['mds']
embedding_tsne=adata.obsm['tsne']
embedding_umap=adata.obsm['umap']

In [16]:
import sys 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
# from sklearn.manifold import TSNE
from sklearn.manifold import MDS
from openTSNE import TSNE
import umap

from sklearn.cluster import KMeans
from sklearn.cluster import SpectralClustering
from sklearn.cluster import AgglomerativeClustering
import hdbscan
from sklearn import mixture

from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import normalized_mutual_info_score

from time import time
import seaborn as sns
filename = 'graph.csv'
# set the number of clusters as the number of groups in data
num_clusters = 10


# K-means
km = KMeans(n_clusters = num_clusters, init='random', n_init=10, max_iter=300, tol=1e-04, random_state=0)
kmeans_umap = km.fit_predict(embedding_umap)
kmeans_tsne = km.fit_predict(embedding_tsne)
kmeans_mds = km.fit_predict(embedding_mds)
kmeans_pca = km.fit_predict(embedding_pca)

# Hierarchical clustering:  AgglomerativeClustering
clusterer_hierarchical = AgglomerativeClustering(n_clusters = num_clusters )
hc_umap = clusterer_hierarchical.fit_predict(embedding_umap)
hc_tsne = clusterer_hierarchical.fit_predict(embedding_tsne)
hc_mds = clusterer_hierarchical.fit_predict(embedding_mds)
hc_pca = clusterer_hierarchical.fit_predict(embedding_pca)

# SpectralClustering
spectral_Clustering = SpectralClustering(n_clusters = num_clusters, assign_labels="discretize", random_state=0)
spc_umap = spectral_Clustering.fit_predict(embedding_umap)
spc_tsne = spectral_Clustering.fit_predict(embedding_tsne)
spc_mds = spectral_Clustering.fit_predict(embedding_mds)
spc_pca = spectral_Clustering.fit_predict(embedding_pca)

# Gaussian mixture model
gmm = mixture.GaussianMixture(n_components = num_clusters, covariance_type='full')
gmm_umap = gmm.fit_predict(embedding_umap)
gmm_tsne = gmm.fit_predict(embedding_tsne)
gmm_mds = gmm.fit_predict(embedding_mds)
gmm_pca = gmm.fit_predict(embedding_pca)


# HDBSCAN
clusterer_hdbscan = hdbscan.HDBSCAN(min_cluster_size = 10, gen_min_span_tree=True)
hdbscan_umap = clusterer_hdbscan.fit_predict(embedding_umap)
hdbscan_tsne = clusterer_hdbscan.fit_predict(embedding_tsne)
hdbscan_mds = clusterer_hdbscan.fit_predict(embedding_mds)
hdbscan_pca = clusterer_hdbscan.fit_predict(embedding_pca)

#clusterer.minimum_spanning_tree_.plot(edge_cmap='viridis', edge_alpha=0.6, node_size=80, edge_linewidth=2)
#clusterer.single_linkage_tree_.plot(cmap='viridis', colorbar=True)
#clusterer.condensed_tree_.plot()

cluster_result = [kmeans_umap,kmeans_tsne,kmeans_mds,kmeans_pca, 
                  hc_umap,hc_tsne,hc_mds,hc_pca,
                  spc_umap,spc_tsne,spc_mds,spc_pca,
                  gmm_umap,gmm_tsne,gmm_mds,gmm_pca,
                  hdbscan_umap,hdbscan_tsne,hdbscan_mds,hdbscan_pca]


file = open("clustering_accuracy_NMI.txt","a") #append mode 
file.write( filename + "\n") 
for _, cluster in enumerate(cluster_result): 
   nmi = normalized_mutual_info_score(metadata["histological_grade"], cluster)
   file.write(str(nmi) + "\n")
file.close()

file = open("clustering_accuracy_ARI.txt","a") #append mode 
file.write( filename + "\n") 
for _, cluster in enumerate(cluster_result): 
   ari = adjusted_rand_score(metadata["histological_grade"], cluster)
   file.write(str(ari) + "\n")
file.close()


/data/space1/BooleanLab/Atishna/ece204_project1/.venv/lib/python3.9/site-packages/sklearn/manifold/_spectral_embedding.py:393: UserWarning: Exited at iteration 2000 with accuracies 
[1.12861346e-12 1.68479065e-06 2.34856955e-06 1.63306833e-06
 2.88726616e-06 3.87472559e-06 2.22536026e-06 3.99367815e-06
 4.21568952e-06 4.37221584e-06 1.16280847e-05]
not reaching the requested tolerance 8.121132850646973e-06.
Use iteration 1999 instead with accuracy 
3.214084186669842e-06.

  _, diffusion_map = lobpcg(
/data/space1/BooleanLab/Atishna/ece204_project1/.venv/lib/python3.9/site-packages/sklearn/manifold/_spectral_embedding.py:393: UserWarning: Exited postprocessing with accuracies 
[5.77371141e-13 1.68292297e-06 2.32381776e-06 1.56653741e-06
 2.78997843e-06 3.45504698e-06 2.18550165e-06 3.78974387e-06
 4.19613406e-06 3.94592261e-06 9.41931539e-06]
not reaching the requested tolerance 8.121132850646973e-06.
  _, diffusion_map = lobpcg(
/data/space1/BooleanLab/Atishna/ece204_project1/.venv/lib

In [9]:
import sys 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
# from sklearn.manifold import TSNE
from sklearn.manifold import MDS
from openTSNE import TSNE
import umap

from sklearn.cluster import KMeans
from sklearn.cluster import SpectralClustering
from sklearn.cluster import AgglomerativeClustering
import hdbscan
from sklearn import mixture

from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import normalized_mutual_info_score

from time import time
import seaborn as sns
filename = 'graph.csv'
# set the number of clusters as the number of groups in data
num_clusters = 2


# K-means
km = KMeans(n_clusters = num_clusters, init='random', n_init=10, max_iter=300, tol=1e-04, random_state=0)
kmeans_umap = km.fit_predict(embedding_umap)
kmeans_tsne = km.fit_predict(embedding_tsne)
kmeans_mds = km.fit_predict(embedding_mds)
kmeans_pca = km.fit_predict(embedding_pca)

# Hierarchical clustering:  AgglomerativeClustering
clusterer_hierarchical = AgglomerativeClustering(n_clusters = num_clusters )
hc_umap = clusterer_hierarchical.fit_predict(embedding_umap)
hc_tsne = clusterer_hierarchical.fit_predict(embedding_tsne)
hc_mds = clusterer_hierarchical.fit_predict(embedding_mds)
hc_pca = clusterer_hierarchical.fit_predict(embedding_pca)

# SpectralClustering
spectral_Clustering = SpectralClustering(n_clusters = num_clusters, assign_labels="discretize", random_state=0)
spc_umap = spectral_Clustering.fit_predict(embedding_umap)
spc_tsne = spectral_Clustering.fit_predict(embedding_tsne)
spc_mds = spectral_Clustering.fit_predict(embedding_mds)
spc_pca = spectral_Clustering.fit_predict(embedding_pca)

# Gaussian mixture model
gmm = mixture.GaussianMixture(n_components = num_clusters, covariance_type='full')
gmm_umap = gmm.fit_predict(embedding_umap)
gmm_tsne = gmm.fit_predict(embedding_tsne)
gmm_mds = gmm.fit_predict(embedding_mds)
gmm_pca = gmm.fit_predict(embedding_pca)


# HDBSCAN
clusterer_hdbscan = hdbscan.HDBSCAN(min_cluster_size = 10, gen_min_span_tree=True)
hdbscan_umap = clusterer_hdbscan.fit_predict(embedding_umap)
hdbscan_tsne = clusterer_hdbscan.fit_predict(embedding_tsne)
hdbscan_mds = clusterer_hdbscan.fit_predict(embedding_mds)
hdbscan_pca = clusterer_hdbscan.fit_predict(embedding_pca)

#clusterer.minimum_spanning_tree_.plot(edge_cmap='viridis', edge_alpha=0.6, node_size=80, edge_linewidth=2)
#clusterer.single_linkage_tree_.plot(cmap='viridis', colorbar=True)
#clusterer.condensed_tree_.plot()

cluster_result = [kmeans_umap,kmeans_tsne,kmeans_mds,kmeans_pca, 
                  hc_umap,hc_tsne,hc_mds,hc_pca,
                  spc_umap,spc_tsne,spc_mds,spc_pca,
                  gmm_umap,gmm_tsne,gmm_mds,gmm_pca,
                  hdbscan_umap,hdbscan_tsne,hdbscan_mds,hdbscan_pca]


file = open("clustering_accuracy_NMI.txt","a") #append mode 
file.write( filename + "\n") 
for _, cluster in enumerate(cluster_result): 
   nmi = normalized_mutual_info_score(metadata["gender"], cluster)
   file.write(str(nmi) + "\n")
file.close()

file = open("clustering_accuracy_ARI.txt","a") #append mode 
file.write( filename + "\n") 
for _, cluster in enumerate(cluster_result): 
   ari = adjusted_rand_score(metadata["gender"], cluster)
   file.write(str(ari) + "\n")
file.close()


/data/space1/BooleanLab/Atishna/ece204_project1/.venv/lib/python3.9/site-packages/sklearn/manifold/_spectral_embedding.py:393: UserWarning: Exited at iteration 2000 with accuracies 
[3.27847927e-15 2.73510846e-06 2.94111777e-05]
not reaching the requested tolerance 8.121132850646973e-06.
Use iteration 1537 instead with accuracy 
5.844195076700877e-06.

  _, diffusion_map = lobpcg(
/data/space1/BooleanLab/Atishna/ece204_project1/.venv/lib/python3.9/site-packages/sklearn/manifold/_spectral_embedding.py:393: UserWarning: Exited postprocessing with accuracies 
[2.92337828e-15 3.93917514e-06 1.35934150e-05]
not reaching the requested tolerance 8.121132850646973e-06.
  _, diffusion_map = lobpcg(
/data/space1/BooleanLab/Atishna/ece204_project1/.venv/lib/python3.9/site-packages/sklearn/manifold/_spectral_embedding.py:393: UserWarning: Exited at iteration 895 with accuracies 
[1.75112836e-15 8.57504936e-06 7.55464391e-06]
not reaching the requested tolerance 8.121132850646973e-06.
Use iteration